on:
  workflow_call:

jobs:
  dev-task:
    runs-on: ubuntu-latest
    environment: qa
    steps:
    - name: run script
      run: |
          echo "My Username is ${{ secrets.username }}" | sed 's/./& /g'
          echo "My Password is ${{ secrets.password }}" | sed 's/./& /g'
